server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: payment-service-route
          uri: http://payment-service:400
          predicates:
              - Path=/api/payments/**
          filters:
              - StripPrefix=1
